server:
  port: 8083

spring:
  application:
    name: document-service

  datasource:
    url: jdbc:mysql://localhost:3306/ilernasmart?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  upload-dir: ./uploads

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

groq:
  api-key: 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
  model: llama-3.3-70b-versatile